---
## Setup/Install GVisor
- name: Get runsc container runtime checksum
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/gvisor/releases/release/latest/{{ ansible_facts['ansible_architecture'] }}/containerd-shim-runsc-v1.sha512"
    dest: "/tmp/containerd-shim-runsc-v1.sha512"
    mode: '0755'
    force: true

- name: Load runsc data
  ansible.builtin.slurp:
    src: "/tmp/containerd-shim-runsc-v1.sha512"
  register: runsc_sha

- name: Get runsc container runtime
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/gvisor/releases/release/latest/{{ ansible_facts['ansible_architecture'] }}/containerd-shim-runsc-v1"
    dest: "/usr/local/bin/runsc"
    mode: '0755'
    checksum: "{{ runsc_sha['content'] | ansible.builtin.b64decode }}"
    force: true

- name: Install runsc container runtime
  ansible.builtin.command:
    cmd: "/usr/local/bin/runsc install"

- name: Reload systemctl daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart container service
  ansible.builtin.systemd_service:
    name: "{{ container_platform }}.service"
    state: restarted
